# Generated by Django 3.2.8 on 2021-11-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True, verbose_name='Ngày tạo')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(default='', max_length=500, verbose_name='URL')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Ngày tạo')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên sản phẩm')),
                ('unique_product', models.CharField(default='', max_length=20, verbose_name='UID sản phẩm')),
                ('slug', models.SlugField(default='', max_length=500, verbose_name='URL')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='quote.category')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Tên dung tích')),
                ('unique_volume', models.CharField(default='', max_length=20, verbose_name='UID Dung tích')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_product', to='quote.product')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên bao bì')),
                ('price', models.FloatField(default=0, verbose_name='Giá bao bì')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên nguyên liệu')),
                ('price', models.FloatField(default=0, verbose_name='Giá nguyên liệu')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
        ),
        migrations.CreateModel(
            name='Carton_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên thùng caton')),
                ('price', models.FloatField(default=0, verbose_name='Giá thùng caton')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
        ),
        migrations.CreateModel(
            name='Box_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên hộp đựng sản phẩm')),
                ('price', models.FloatField(default=0, verbose_name='Giá hộp đựng sản phẩm')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
        ),
    ]
