# Generated by Django 3.2.8 on 2021-12-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên gói công bố kiểm nghiệm')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='FeeShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên gói phí vận chuyển')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên bao bì cấp 1')),
                ('type_packaging', models.CharField(default='', max_length=50, verbose_name='Loại bao bì')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='media/upload/images/2021/12', verbose_name='Image')),
                ('type_material', models.CharField(default='', max_length=255, verbose_name='Chất liệu')),
                ('quantity_provider_sell', models.IntegerField(default=0, verbose_name='Chất liệu NCC có thể bán')),
                ('min_order', models.IntegerField(default=0, verbose_name='Min order')),
                ('provider', models.CharField(default='', max_length=255, verbose_name='Nhà cung cấp')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('quantity_can_order_with_price', models.IntegerField(default=0, verbose_name='Số lượng đặt hàng tương ứng với giá')),
                ('time_to_send', models.TextField(default='', verbose_name='Thời gian giao hàng')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên bao bì cấp 2')),
                ('price', models.FloatField(default=0, verbose_name='Giá bao bì')),
                ('type_packaging', models.CharField(default='', max_length=50, verbose_name='Loại bao bì')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='PackingWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên gói chi phí công nhân đóng gói')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên tem nhãn')),
                ('type_stamp', models.CharField(default='', max_length=255, verbose_name='Loại tem nhãn')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
        ),
        migrations.RemoveField(
            model_name='carton_box',
            name='product',
        ),
        migrations.RemoveField(
            model_name='carton_box',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='product',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='volume',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_activate',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='is_activate',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_activate',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='is_activate',
            new_name='status',
        ),
        migrations.DeleteModel(
            name='Box_Product',
        ),
        migrations.DeleteModel(
            name='Carton_Box',
        ),
        migrations.DeleteModel(
            name='Packaging',
        ),
        migrations.AddField(
            model_name='stamp',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_product', to='quote.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_volume', to='quote.volume', verbose_name='Dung tích'),
        ),
        migrations.AddField(
            model_name='packingworker',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_worker_product', to='quote.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='packingworker',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_worker_volume', to='quote.volume', verbose_name='Dung tích'),
        ),
        migrations.AddField(
            model_name='packaginglevel2',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_product', to='quote.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='packaginglevel2',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_volume', to='quote.volume', verbose_name='Dung tích'),
        ),
        migrations.AddField(
            model_name='packaginglevel1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_level_1_product', to='quote.product'),
        ),
        migrations.AddField(
            model_name='packaginglevel1',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagin_level1_volume', to='quote.volume', verbose_name='Dung tích'),
        ),
        migrations.AddField(
            model_name='feeshipping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_shipping_product', to='quote.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='feeshipping',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_shipping_volume', to='quote.volume', verbose_name='Dung tích'),
        ),
        migrations.AddField(
            model_name='announced',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonced_product', to='quote.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='announced',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonced_volume', to='quote.volume', verbose_name='Dung tích'),
        ),
    ]
