# Generated by Django 3.2.9 on 2021-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20211201_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Sản Phẩm'},
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/products/2021/12', verbose_name='Image'),
        ),
    ]
