# Generated by Django 3.2.9 on 2021-12-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20211201_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announced',
            options={'ordering': ['name'], 'verbose_name': 'Công bố kiểm nghiệm', 'verbose_name_plural': 'Công bố kiểm nghiệm'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục sản phẩm', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='feeshipping',
            options={'ordering': ['name'], 'verbose_name': 'Vận chuyển', 'verbose_name_plural': 'Vận chuyển'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Nguyên liệu', 'verbose_name_plural': 'Nguyên liệu'},
        ),
        migrations.AlterModelOptions(
            name='packaginglevel1',
            options={'ordering': ['name'], 'verbose_name': 'Bao bì cấp 1', 'verbose_name_plural': 'Bao bì cấp 1'},
        ),
        migrations.AlterModelOptions(
            name='packaginglevel2',
            options={'ordering': ['name'], 'verbose_name': 'Bao bì cấp 2', 'verbose_name_plural': 'Bao bì cấp 2'},
        ),
        migrations.AlterModelOptions(
            name='packingworker',
            options={'ordering': ['name'], 'verbose_name': 'Nhân công đóng gói', 'verbose_name_plural': 'Nhân công đóng gói'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Sản Phẩm', 'verbose_name_plural': 'Sản Phẩm'},
        ),
        migrations.AlterModelOptions(
            name='stamp',
            options={'ordering': ['name'], 'verbose_name': 'Tem nhãn', 'verbose_name_plural': 'Tem nhãn'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['name'], 'verbose_name': 'Dung tích sản phẩm', 'verbose_name_plural': 'Dung tích sản phẩm'},
        ),
    ]
