# Generated by Django 3.2.8 on 2021-12-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_product',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='UID sản phẩm'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='unique_volume',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='UID Dung tích'),
        ),
    ]
