# Generated by Django 3.2.8 on 2021-12-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20211202_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL'),
        ),
    ]
