# Generated by Django 3.2.8 on 2021-12-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ghi chú'),
        ),
    ]
